services:
  docker-kindle:
    image: ghcr.io/mathiasdpx/docker-kindle:latest
    container_name: docker-kindle
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped
    environment:
      - GIN_MODE=release